### ISSUE TITLE
Kinematics Issues

### ISSUE THREAD

**Issue by lpsantao** [Sarrasor/RoboticManipulators#1]
Hi, I have tried to compare the results of your forward kinematics with the values given in Roboguide (Fanuc official simulator) and also with the real robot, and the values when moving joint 2 are not correct, all other joints work, when moving joint 2 it does not give correct values for the end-effector position. Any idea what is happening?

Thank you for your work and time!

**Comment by Sarrasor** [comment]
Hi, thanks for letting me know!

I think, the problem is in the joint offsets and rotation directions

Some joints in FK transformations might be offset from the real joints by
some angle or the rotation directions might differ (if I'm not mistaken,
some joints on Fanuc rotate clockwise, while some - counterclockwise)

I will check this issue next week, meanwhile you can try to tinker with FK
from 'fanuc_calibration.py' (lines 32-36). There you can set rotation
directions. Current values of joint lengths and rotation directions in the
file are from the real Fanuc

**Comment by lpsantao** [comment]
Hello again, thanks for the prompt answer !

I have figured the problem, turns out all Fanuc robots have a J2/J3 coupling configured that compensates the J3 angle to keep J3 in the same position relative to J2 when jogging J2. So basically, J3 = J3+J2, this way the forward kinematics is correct :) 

If you want more details: http://wiki.ros.org/fanuc_driver/Troubleshooting#J3_on_TP_and_joint_3_in_ROS_do_not_match

Thank you once again for your work and time! Hope this helps you also :)
